FROM python:3.7.4-slim-buster

USER root

RUN apt update -y
RUN apt install gcc -y
RUN apt install git -y 

RUN apt-get -y install \
	build-essential 

RUN pip install matplotlib
RUN pip install numpy
RUN pip install pandas
RUN pip install seaborn
RUN pip install scikit-learn
RUN pip install xgboost==1.6.2
RUN pip install git+https://github.com/intelligent-environments-lab/CityLearn.git@v1.3.5

RUN git config --global --add safe.directory /app
RUN git config --global --add safe.directory '*'
RUN mkdir /home/aicrowd

WORKDIR /home
